### ISSUE TITLE
Problème de KeyError

### ISSUE THREAD

**Issue by Teyk0o** [busybox11/probote#5]
Bonjour, quand je lance le main.py après avoir tout configurer j'ai une erreur "KeyError: 'success'"

**Comment by busybox11** [comment]
Bonjour,
Cela signifie que vos informations de connexions sont erronées.
Veuillez les revérifier, et les reconfigurer correctement si nécessaire (pensez au CAS !)

**Comment by Teyk0o** [comment]
username = "username"
password = "password"
url = "https://0180036s.index-education.net/pronote"
cas = "ac-orleans-tours"
token = "token"
admin = 673103452250832901
probote_channel = 687021227222630420

J'ai censuré quelques infos mais tout est bon sinon ?

**Comment by busybox11** [comment]
Normalement oui.
Le serveur NodeJS est lancé et accessible ?

**Comment by Teyk0o** [comment]
L'erreur vient sûrement de là, les logs : 
Error: Request failed with status code 404
